# 将来的には対応する規約の読込
inherit_from: .rubocop_todo.yml

# 追加した規約ファイル読込
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  # 除外
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false


Layout/EmptyLinesAroundAttributeAccessor:
  Description: "Checks for a newline after an attribute accessor or a group of them."
  Enabled: true
  VersionAdded: "0.83"
  VersionChanged: "0.84"

Layout/SpaceAroundMethodCallOperator:
  Description: "Checks method call operators to not have spaces around them."
  Enabled: true
  VersionAdded: "0.82"

Lint/DeprecatedOpenSSLConstant:
  Description: "Algorithmic constants for OpenSSL::Cipher and OpenSSL::Digest deprecated since OpenSSL version 2.2.0. Prefer passing a string instead."
  Enabled: true
  VersionAdded: "0.84"

Lint/DuplicateElsifCondition:
  Description: "This cop checks that there are no repeated conditions used in if 'elsif'."
  Enabled: true
  VersionAdded: "0.88"

Lint/MixedRegexpCaptureTypes:
  Description: "Do not mix named captures and numbered captures in a Regexp literal because numbered capture is ignored if they’re mixed."
  Enabled: true
  VersionAdded: "0.85"

Lint/RaiseException:
  Description: "This cop checks for raise or fail statements which are raising Exception class."
  Enabled: true
  Safe: true
  VersionAdded: "0.81"

Lint/StructNewOverride:
  Description: "This cop checks unexpected overrides of the Struct built-in methods via Struct.new."
  Enabled: true
  VersionAdded: "0.81"

Lint/BinaryOperatorWithIdenticalOperands:
  Description: "This cop checks for places where binary operator has identical operands."
  Enabled: true
  VersionAdded: "0.89"

Lint/DuplicateRescueException:
  Description: "This cop checks that there are no repeated exceptions used in 'rescue' expressions."
  Enabled: true
  VersionAdded: "0.89"

Lint/EmptyConditionalBody:
  Description: "This cop checks for the presence of if, elsif and unless branches without a body."
  Enabled: true
  VersionAdded: "0.89"

Lint/FloatComparison:
  Description: "This cop checks for the presence of precise comparison of floating point numbers."
  Enabled: true
  VersionAdded: "0.89"

Lint/MissingSuper:
  Description: "This cop checks for the presence of constructors and lifecycle callbacks without calls to super."
  Enabled: true
  VersionAdded: "0.89"

Lint/OutOfRangeRegexpRef:
  Description: "This cops looks for references of Regexp captures that are out of range and thus always returns nil."
  Enabled: true
  VersionAdded: "0.89"

Lint/SelfAssignment:
  Description: "This cop checks for self-assignments."
  Enabled: true
  VersionAdded: "0.89"

Lint/TopLevelReturnWithArgument:
  Description: "This cop checks for top level return with arguments. If there is a top-level return statement with an argument, then the argument is always ignored. This is detected automatically since Ruby 2.7."
  Enabled: true
  VersionAdded: "0.89"

Lint/UnreachableLoop:
  Description: "This cop checks for loops that will have at most one iteration."
  Enabled: true
  VersionAdded: "0.89"

RSpec/Capybara/FeatureMethods:
  Enabled: false